pipeline {
    agent {
        label 'slave-ubuntu'
    }

    environment {
        K8S_DEPLOYMENT_NAME = 'admin-service'
        K8S_SSH_INFO = 'admin@192.168.8.230'
        REGISTRY_URL = 'vmapi/quanlyxe'
        IMAGE_TAG = 'vietmap.tracking.adminservice'
        VERSION = "1.0.0.${params.buildNumber}"
    }

    stages {      
        stage('Deploy') {
            steps {
                sshagent(['ssh-k8s-testing']) {
                    sh "ssh ${K8S_SSH_INFO} 'kubectl set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${REGISTRY_URL}:${IMAGE_TAG}.${VERSION}'"
                }
            }
        }
    }
}
